build:
  zip:
    pack:
      excludes:
        paths:
          - "README.md"
          - "phpunit.xml"
          - ".shopware-extension.yml"
          - ".github"
          - ".gitignore"
          - "tests"
